CREATE TABLE LICENSE(
	L_SEQ NUMBER NOT NULL PRIMARY KEY,
	E_IDENNUM NUMBER NOT NULL,
	L_NAME VARCHAR2(100) NOT NULL,
	L_DAY VARCHAR2(20) NOT NULL,
	L_NUM VARCHAR2(20) NOT NULL
)

DROP TABLE LICENSE

ALTER TABLE LICENSE
ADD CONSTRAINT FK_L_E_IDENNUM FOREIGN KEY(E_IDENNUM) REFERENCES EMPLOYEE(E_IDENNUM)

create sequence L_SEQ
increment by 1
start with 1
maxvalue 99999999