CREATE TABLE SCHOOL(
	S_SEQ NUMBER NOT NULL PRIMARY KEY,
	E_IDENNUM NUMBER NOT NULL,
	S_NAME VARCHAR2(50) NOT NULL,
	S_MAJOR VARCHAR2(20) NOT NULL,
	S_START VARCHAR2(10) NOT NULL,
	S_END VARCHAR2(10) NOT NULL
)

DROP TABLE SCHOOL

ALTER TABLE SCHOOL
ADD CONSTRAINT FK_S_E_IDENNUM FOREIGN KEY(E_IDENNUM) REFERENCES EMPLOYEE(E_IDENNUM)

create sequence S_SEQ
increment by 1
start with 1
maxvalue 99999999